---
slug: foobar
filename: foobar
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 68d8aeab-ff66-415c-a739-8d019e77d2b7
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
